<?php
$string['modulename'] = 'Interactive Video';
$string['modulenameplural'] = 'Interactive Videos';
$string['modulename_help'] = 'The Interactive Video module allows teachers to create video lessons with embedded interactions such as quizzes, notes, and hotspots.';
$string['pluginname'] = 'Interactive Video';
$string['pluginadministration'] = 'Interactive Video administration';
$string['ivplayer:addinstance'] = 'Add a new Interactive Video';
$string['ivplayer:view'] = 'View Interactive Video';
$string['vimeoid'] = 'Vimeo URL or ID';
$string['vimeoid_help'] = 'Enter the Vimeo video URL (e.g., https://vimeo.com/123456789/abcdef) or just the numeric ID.';
$string['interactions'] = 'Interactions (JSON)';
$string['interactions_help'] = 'Paste the JSON configuration generated by the visual configurator. Use the configurator at the provided URL to create this JSON easily.';
$string['completioninteractions'] = 'Student must watch the video and complete all interactions';
$string['completiondetail:interactions'] = 'Watch the video and complete all interactions';
